name: Run tests

on:
  workflow_call:
    inputs:
      package:
        description: api | ui
        required: true
        type: string

jobs:
  validate-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup maven wrapper
        run: chmod +x mvnw

      - name: Validate Checkstyle
        run: ./mvnw validate

  run-tests:
    needs: validate-checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: TeamCity Setup
        uses: ./.github/actions/teamcity-setup

      - name: Wait for TeamCity to be ready
        run: |
          for i in {1..10}; do
            curl -s http://$HOST:8111 | grep "TeamCity" && break
            echo "Waiting for TeamCity..."
            sleep 15
          done

      - name: Run tests
        continue-on-error: true
        run: ./mvnw test -Dtest='org.example.teamcitypro.${{ inputs.package }}.**' -Dgroups=Regression

      - name: Save Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-results
